name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # ... existing steps ...

      - name: Install dependencies
        run: npm install

      # New step to run tests
      - name: Run tests
        run: npm test

      # ... existing steps ... 